#!/bin/bash

[ "${DEBUG:-}" = "yes" ] && set -x

# PHP ignores TZ, so pass it on as the default timezone
if [[ -n "$TZ" ]]; then
    echo "date.timezone = $TZ" > "$PHP_INI_DIR/conf.d/zz-timezone.ini"
fi

CONFIG_DIR="$HORDE_DIR/var/config"
CONFIG_DIST=/usr/local/share/horde/config-dist
CONF_PHP="$CONFIG_DIR/horde/conf.php"

# Sync the files generated by the Horde installer into the config volume.
# *.dist, horde.local.php and files marked "WILL BE OVERWRITTEN" belong to the
# image and are always refreshed; anything else is only copied if missing so
# admin edits are never lost.
(cd "$CONFIG_DIST" && find . -type f) | while read -r f; do
    mkdir -p "$(dirname "$CONFIG_DIR/$f")"
    if [[ "$f" == *.dist || "$f" == */horde.local.php ]] || grep -q "WILL BE OVERWRITTEN" "$CONFIG_DIST/$f"; then
        cp -f "$CONFIG_DIST/$f" "$CONFIG_DIR/$f"
    elif [[ ! -e "$CONFIG_DIR/$f" ]]; then
        cp "$CONFIG_DIST/$f" "$CONFIG_DIR/$f"
    fi
done

if [[ ! -f "$CONF_PHP" ]]; then
    cp "$CONFIG_DIR/horde/conf.php.dist" "$CONF_PHP"
    cat /etc/horde-base-settings.inc >> "$CONF_PHP"
fi

# Horde 6 refuses to start without a secret key, generate one if it is missing or empty
if ! grep -qE "^\\\$conf\['secret_key'\] = '.+';" "$CONF_PHP"; then
    sed -i "/^\$conf\['secret_key'\]/d" "$CONF_PHP"
    printf "\n\$conf['secret_key'] = '%s';\n" "$(php -r 'echo bin2hex(random_bytes(32));')" >> "$CONF_PHP"
fi

# conf.php.dist has no share driver until the config is saved in the admin UI, and the
# Kronolith schema migration fails without one. Use Horde's default.
if ! grep -q "^\$conf\['share'\]\['driver'\]" "$CONF_PHP"; then
    printf "\$conf['share']['driver'] = 'Sqlng';\n" >> "$CONF_PHP"
fi

# Legacy --link mysql:mysql variables
if [[ $MYSQL_PORT_3306_TCP_ADDR ]]; then
    DB_HOST=$MYSQL_PORT_3306_TCP_ADDR
    DB_PORT=$MYSQL_PORT_3306_TCP_PORT
    DB_PROTOCOL=tcp
fi
if [[ $MYSQL_ENV_MYSQL_ROOT_PASSWORD ]]; then
    DB_USER=root
    DB_PASS=$MYSQL_ENV_MYSQL_ROOT_PASSWORD
fi
DB_SOCKET=${DB_SOCKET:-/var/run/mysqld/mysqld.sock}

php_quote() {
    printf "'%s'" "$(printf '%s' "$1" | sed "s/[\\\\']/\\\\&/g")"
}

# Current MySQL/MariaDB servers no longer accept the plain "utf8" charset name
# that the Horde 5 default of 'utf-8' maps to
sed -i "s/^\(\$conf\['sql'\]\['charset'\] = \)'utf-\?8';/\1'utf8mb4';/" "$CONF_PHP"

# Rewrite the DB connection settings in conf.php from the environment. Horde 6
# rejects a host and a socket together, so only write the ones for DB_PROTOCOL.
sed -i "/^\$conf\['sql'\]\['\(username\|password\|database\|phptype\|protocol\|hostspec\|port\|socket\)'\]/d" "$CONF_PHP"
{
    echo "\$conf['sql']['username'] = $(php_quote "$DB_USER");"
    echo "\$conf['sql']['password'] = $(php_quote "$DB_PASS");"
    echo "\$conf['sql']['database'] = $(php_quote "$DB_NAME");"
    echo "\$conf['sql']['phptype'] = $(php_quote "$DB_DRIVER");"
    if [[ "${DB_PROTOCOL,,}" == "tcp" ]]; then
        echo "\$conf['sql']['protocol'] = 'tcp';"
        echo "\$conf['sql']['hostspec'] = $(php_quote "$DB_HOST");"
        echo "\$conf['sql']['port'] = $(php_quote "$DB_PORT");"
    else
        echo "\$conf['sql']['protocol'] = 'unix';"
        echo "\$conf['sql']['socket'] = $(php_quote "$DB_SOCKET");"
    fi
} >> "$CONF_PHP"

MYSQL_ARGS=(-u "$DB_USER" --password="$DB_PASS" --skip-column-names)
if [[ "${DB_PROTOCOL,,}" == "tcp" ]]; then
    MYSQL_ARGS+=(--protocol=tcp --host="$DB_HOST" --port="$DB_PORT")
else
    MYSQL_ARGS+=(--protocol=socket --socket="$DB_SOCKET")
fi

if ! RESULT=$(mysql "${MYSQL_ARGS[@]}" -e "SHOW DATABASES LIKE '$DB_NAME'"); then
    echo "Cannot connect to the database server, check the DB_* settings; skipping database setup" >&2
elif [ "$RESULT" == "$DB_NAME" ]; then
    echo "Database exist"
else
    echo "Database does not exist"
    if mysql "${MYSQL_ARGS[@]}" -e "CREATE DATABASE \`$DB_NAME\`" \
        && horde-db-migrate content && horde-db-migrate; then
        echo "Database created"
    else
        echo "Creating database $DB_NAME failed" >&2
    fi
fi

# Fix file/dir permissions
chown -R www-data:www-data "$HORDE_DIR/var" "$HORDE_DIR/web/static"
